# ===============================
# BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/reminderu_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=danielRobles
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# HIBERNATE / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# THYMELEAF
# ===============================
spring.thymeleaf.cache=false

# ===============================
# PUERTO DEL SERVIDOR
# ===============================
server.port=8080

# ===============================
# ENVÍO DE CORREOS (GMAIL)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=24reminderu@gmail.com
spring.mail.password=sixi xoxb tlqm veqn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# LOGIN GOOGLE (OAUTH2)
# ===============================
spring.security.oauth2.client.registration.google.client-id=39541099388-k8voalbt73hmi0j1osokv0vggr46pkbk.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://www.googleapis.com/oauth2/v4/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# ===============================
# LOGS
# ===============================
logging.level.org.springframework=INFO
logging.level.com.reminderU=DEBUG
